In [6]:
import numpy as np



In [7]:
list=(1,2,3)
list
np.array(list)


array([1, 2, 3])

In [8]:
list=[1,23,34]
y=np.array(list)
type(y)


numpy.ndarray

In [9]:
list=[6,4]
np.ones(list)
np.eye(1,10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
list=[3,2]
np.zeros(list)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [12]:
list=np.array([1,2,3,4,5,6])
li=list.reshape(3,2)
li

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
list=[12,13,14,15]
np.sqrt(list)

array([3.46410162, 3.60555128, 3.74165739, 3.87298335])

In [14]:
np.argmin(list)

np.int64(0)

In [21]:
 # work on 1d
np.median(list)

np.float64(13.5)

In [23]:
np.mean(list)

np.float64(13.5)

In [25]:
np.transpose((list))

array([12, 13, 14, 15])

In [34]:
np.mean(list)

np.float64(13.5)

In [35]:
np.shape(list)

(4,)

In [37]:
np.acos(list)

C:\Users\HP\AppData\Local\Temp\ipykernel_15624\4100451474.py:1: RuntimeWarning: invalid value encountered in arccos
  np.acos(list)


array([nan, nan, nan, nan])

In [41]:
#Work on 3D
arr3d= np.ndarray((5,5,10))
random_num = arr3d[1,2,5]
print("random element at block 2, row 3, coloumn 4:",random_num)

random element at block 2, row 3, coloumn 4: 9.091327223334035e+276


In [2]:
import numpy as np


In [3]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [5]:
list=np.arange(1,4)
list

array([1, 2, 3])

In [8]:
import numpy as np
array2d=np.array([[1,2,3]])
print(array2d)

[[1 2 3]]


In [9]:
import numpy as np
array3d=np.array([[[1,2,3],[4,5,6]]])
print(array3d)

[[[1 2 3]
  [4 5 6]]]


In [1]:
import pandas a pd

SyntaxError: invalid syntax (3297036311.py, line 1)